### ISSUE TITLE
Header Does't work on Error 404 page

### ISSUE THREAD

**Issue by PriyanshuRj** [plone/plone.org#108] opened 2023-03-19 11:45 UTC
Visit the URL :  https://plone.org/ 
Append any random string on the end of URL to react error 404 page for example https://plone.org/fd
the header on this page don't respond while the footer does

*Expected Behavior*
The Header should work and redirect to the required pages

**Comment by Fosten** [comment] 2023-08-18 19:36
My React Developer Tools shows "This page doesn't appear to be using React."

Header and footer seem to display correctly otherwise.

<img width="1250" alt="Screen Shot 2023-08-18 at 3 27 40 PM" src="https://github.com/plone/plone.org/assets/1520484/f24a5cd4-b85d-4738-9cd0-ed2c1bf989c5">

**Comment by davisagli** [comment] 2023-08-18 19:54
This is caused by #98, so I'll close this as a duplicate.

**Closed as not planned by davisagli** 2023-08-18 19:54 UTC
